### ISSUE TITLE
Forced function calling does not work for Gemini Flash.

### ISSUE THREAD

**Issue by akos-sch** [langchain-ai/langchain-google#330]
I wrote a script to exemplify the problem I encountered earlier with Gemini Flash forced function calling:

```
from langchain_core.prompts import ChatPromptTemplate
from langchain.pydantic_v1 import BaseModel, Field

from langchain_google_vertexai import ChatVertexAI

llm = ChatVertexAI(
    model="gemini-1.5-flash-preview-0514",
    temperature=0,
    max_retries=2,
)

class SumResult(BaseModel):
    """Result of the sum tool."""
    result: int = Field(description="The sum of the two numbers.")

sum_llm = llm.with_structured_output(SumResult)

system = "You are an assistant helping in adding two numbers. You will be given two numbers and you need to add them together."
human = "Add {num_1} and {num_2}."

prompt = ChatPromptTemplate.from_messages(
        [
            ("system", system),
            ("human", human),
        ]
    )
chain = prompt | sum_llm
print(chain.invoke({"num_1": 3, "num_2": 5}))
```

As you can see, this setup generally tests structured output parsing.
I get the following error:
`google.api_core.exceptions.InvalidArgument: 400 Unable to submit request because the forced function calling (mode = ANY) is only supported for Gemini 1.5 Pro models. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling`

Out of the gemini family on vertex ai, only 1.5 pro supports forced function calling.

This error is valid for lib versions 1.0.5 and 1.0.6, as I validated it works well with 1.0.4.

**Comment by marcelmarais** [comment]
Yes something is wrong here. If you change the model name to `gemini-1.5-flash` it works (by luck I suppose). 

This is because the tool config is dependent on the `is_gemini_advanced` property: 
https://github.com/langchain-ai/langchain-google/blob/7c678dcc59bb4e4d7a1efdbb9572d74b75e87665/libs/vertexai/langchain_google_vertexai/chat_models.py#L1060-L1061

Which is true for these models (notice `gemini-1.5-flash` is missing):
https://github.com/langchain-ai/langchain-google/blob/7c678dcc59bb4e4d7a1efdbb9572d74b75e87665/libs/vertexai/langchain_google_vertexai/_utils.py#L128-L134

If this property is true in `bind_tools` then the function calling mode is set to `ANY` which doesn't work for Gemini Flash.
https://github.com/langchain-ai/langchain-google/blob/7c678dcc59bb4e4d7a1efdbb9572d74b75e87665/libs/vertexai/langchain_google_vertexai/functions_utils.py#L333-L340

**Comment by pelguetat** [comment]
Having the same issue with Flash.

**Comment by syed-al** [comment]
Gemini flash, doesn't support forced function calling. Only Pro-1.5 supports it.

**Comment by akos-sch** [comment]
I understand that now, but it would be great if the library could support structured output parsing even with the Flash model as 1.5 pro is an overkill in most scenarios.

**Comment by shenghann** [comment]
Same issue here observed in version 1.0.6 using `gemini-1.5-flash-001`

**Comment by lkuligin** [comment]
this is the lack of functionaliy on the model's side, closing.

**Comment by pedropcamellon** [comment]
> Gemini flash, doesn't support forced function calling. Only Pro-1.5 supports it.

By this doc from google it does:
- https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling#supported_models

**Comment by 5uperwei** [comment]
Is this problem fixed? I continue experiencing this problem on all gemini models. I'm just testing it with AI studio though. Will the problem continue using API?
